---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: three-tier-app
spec:
  encryptedData:
    DATABASE_URL: AgA5SGuMR0sR+S7Za+CefGnEXNcNf4+mS+u0YRwcPP04HOpXvekzbL4Xg1BLKuRnIqRAb1v5PrFxjka6mkJXhF6EOVSeuW2tyo17V70AJJOSB/KkqWp/nr658TJTIlAy0/ZVuq3FZ3/xere9dl/GemgjKQmw50gsbJ2+tGOOclAtoCyyA0PFKooczA9XRXUut4e0Kgv2uwrXkTHju8AuEBC2gQIbUf7yyOB5ykqOLxuCFHPtTUXWIoqYVYI4YKquGcD4tMV1QPOCOfmUVgIDLamQNm+ATTKhHfNojHVykG41Q1Cr9utffxePt11i4vLb/ChwA2Qy1jv7842bu7es3utGNFq8YeKObKyLu+pin1511aQ0sZujlvC1+1u2JQpcmnxqYp0h6aHjmZJZS9TfvHGhWMv9G7RiP7FU7mIyT9x3Zyn8b6/+HM5r6OW6CapBDlVLoY5XVTRXirE1BQFNZDVugXhW2hcBd0cfkuZzFix3U6rtnJhnvFMApwfu9j/pw68xoYT9PnGh/7DlBqkwTyWS3wN8sTXEMkI3EYTw9HwNtvRQSn5vZBA9w7C5ofAPes0mmvkLUf2/z5PDsP4Rc+9TZSL5K+3esQzPRp8YX8+ECylqZHBhtJBMKq4WKbEuP/VjwWCwZF3VeCjiIbVM7+KxtXo+BHWOkiWs0MbcTWtwUUqYfqlygrTqdt1E6cwMBrew6BBTq4AUqCvZZzAWaLOlgMaB2nxSw3Ih5wvY9TSRt/L0l8/4LcpnlkraYdV8v/JukuQZcNcbJUbScxAHsMit
    JWT_SECRET_KEY: AgAXbF4RNyJovqxpmucTW9LaSn2iGEVZfJIenJhfl/X/VwHWxn6eVDadU3LjblHszlDvFsXrgsCLOQAoe2kGX0ERGFATUVwUbPD+CcQXvAN6I+QXbZi1AIwVO8m5D3uVz7u7kPnz8DFQqxugiK2XKXXCP6eS8TaauHvxFnEh03otNrNoUz3/vY2+Nf4b6SJv+gC5Tm8epXr7qEivaJZiKD08uq2UTK5kxuHokiL31pW0veNdqViqgGcQs2sq3jC1TTMbUCbC0qm8P0+z+0DsG0iCqsyWyboWNwCOPKb0xl5AetEPICtS5tSoZUe9k4mJXewlIXFqfb08WKMLEyS6Q68B7qexrcXADQaKwt3f4wwvwtXyWUcfQtxoZ0KUNHz+AI0ptYVSrQ3p0n63iVxURateKMyr4wwigejCnwRR37kSjvpI3+tmARezZibA/c85TDolsFPSKJ9ADSv8TWKWLuh4/ANoYAqAIoLCH46JHBtoyziUdShPlPcl5B8xbhnq+PTQRCCLcL2lQOlkU/Pli7+0rWTxHD64g78S1tDABwExdVfrzdhn50+v1jHG0OyFNsxNsg3puM8ZzRh28YnIBsTKYN2rk2YZX7D/4O7My3EKKoMSTvLWYb7EFpVd7TwdMk3lXBXzPtiGZ1q0q3OgSuAwD0Qfigs8dWbN9DEplSfvVsj0S0aQx/eRoPZtq8cYsJtDNiQgA39LuDt1sQOY67lveG0EiGdgVAUKhAo0b32ypso97Kz1CXoX3SLyFA==
  template:
    metadata:
      name: backend-secret
      namespace: three-tier-app
    type: Opaque
