---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: three-tier-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBYq5kjzEQNvlem8DT/m5a7v/pyJkfua0L7/gAOUXR2XEXCjKTIBg2wkXcvU/C7qTt0ixSlxM9vEsd6OxSUvCURzz0Pt0CTqiS9cpdIKvttMHYd31O5Ro/k05XNkX6vRD99c47AZjjN16GBZxoQc7Xh4PptJwq7XwvvJgqM4hsYe4/5KStMq4b3w8boJUu22rJdn82AWesTlzbpT3TPBTTLSQAF0ccR4nTblSJi3NncBlplLPdoxM/s90KbJZ54LHsjTqZCv042fD2suMyc72dPKEZIxSh7vYw3QIgBB5D4+bGJIQhiBCDqxz0E5HhfqL5Mfg3E6fjLPaHR7D3ff6H0c6Nz1Peg7dGvJp//0PYzncXUwIwsM/XDlr0Dl998zIHMam6NlUMpZntU1K1WaNRMj4kJPzwXWEgJh/++pHxOCBl9JwgZivT5JGvtG5PAe6C7JGHxtnIGgcLuc5Yb8LCiBxfAex20ipK+QeqI9rXSpXHY0IDeR4K3EbmJg1QeRWXIhgLvZIxOP6uBqennC26zOLuNX4ZBpFXVoeCMe44lYqoegbPV+0yA3PJLtzKaBvKu1TdAXfsDK20gB/yj9mLKlmbBBP3qrqpANJB/IydtBS8hWCVmQetfgz+ZKSzPJSh98sYKi+SKa1UsNc8PGGGLyIixO6SwW1m0cc4RQWnZbP1HELybfl8QoNzcRdlXMQsFCIPCLuKwnkbsGtcce5s=
    POSTGRES_USER: AgB4ycAGQPG53H4kryPeW4LdpTG+8CFxzpMBFxK2xs13ykJXViQTYGGoj2GCAwhutMgbDfpqvyJYW6VUNwmraO1AK8dNkfGUjMhl7I0cAi7koM5q0K5RAqZTNHjGUWFLq+K6UctKeFDIvQzYsWsdCOrukW3ggnsDR8O3uBF+ys8jAH4MGdNZRiUpIfj0rSTi/HsQvIDapTGF3mCk+g1ODDUkxriLVZHWVXd7AVDqW9axo8q7zkQ9lY6kbUFqtiKaxb3AuY2tw8gjPnQibol/Sy5V9f/IqSrgYLF4ZkP8PzxqkoFuCLEc0cRbzDIPIt6zMcVwfo3f+5bXDwB5b5PilXK+RwIsh0a6cBy7P+w6OZmIf/hl/36/X9ZKDyilz0vYuUoat55E6rWqu5rHajvDdUUIWkVkMBifYzOPaMM7e1qpHozwdzqzvYryXSSoTHD/80761AInO1dT37i3k1PHft4ERY+nMDOX2JdnkHYAzlOCcjw9NAQtxvdsIl/aqBLEgFs4u0KwHgdRCwo2/fd8F1Gqa1QVLoBP0LElh0nOrtCp1ICAI4t4Rrsa/gCCL/H7ISawWesQM9TM2uMOheAhqQWgN3UX0qdn0JhgS14YQbaitKzNrDxM3Por1kD4o+RHbyZpqqMNMrnpl73LncDrLGXzFl3awtKVhuuwoGpchKB1TDwBjZiX211ZIl9nqmDQTl9LVkdgXFVK
  template:
    metadata:
      name: postgres-secret
      namespace: three-tier-app
    type: Opaque
